theme = "awesome-identity"
baseURL = "https://nrfrank.github.io/"
languageCode = 'en-us'
title = "Nathan Frank"


## Profile Configurations
[params]
  colorAwesome = "rgb(37, 87, 162)"

[params.profile]
#  portrait = "images/profile.png"
  portrait = "images/headshot.jpg"
  firstname = "Nathan"
  lastname = "Frank"
  title = "Machine Learning Engineering Leader"
  bio = """Skilled machine learning leader with experience in all aspects of the machine learning and software development life cycle.
Former Astrophysicist turned data scientist and machine learning engineer with a proven history of delivering results into production
across a wide variety of domains while leading projects with international, cross-functional teams.
  """

## Contacts Configurations
[params.contacts]
  email = "nathanryanfrank@gmail.com"
  github = "nrfrank"
#  gitlab = "john.smith"
#  twitter = "john.smith"
#  facebook = "john.smith"
  linkedin = "nrfrank"
#  instagram = "john.smith"
#  stackoverflow = "7919458"
#  keybase = "john.smith"
#  medium = "john.smith"
#  xing = "john.smith"

## Actions (links) configuration
[params.actions.cv]
  name = 'Download My CV'
  url  = 'https://github.com/nrfrank/cv/raw/main/out/cv.pdf'

[params.actions.bisi]
  name = 'BISI (Build It Ship It)'
  url  = 'https://bisi.gitbook.io/bisi/'


## Footer Configurations
[params.footer]
  copyright = "© 2023 Nathan Frank. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
